### ISSUE TITLE
Fabric sampler is loading latents in console but not using them during diffusion

### ISSUE THREAD

**Issue by motelaus** [ssitu/ComfyUI_fabric#19]
<img width="1056" alt="Screenshot 2023-11-18 093428" src="https://github.com/ssitu/ComfyUI_fabric/assets/127054841/ff3fcb72-ce0c-4b39-8b5c-f726ad0f0bf3">

Using latest comfy and fabric versions

**Comment by poisenbery** [comment]
Also having this issue. I swapped to the commit that this was tested on, and I get [This Error.](https://github.com/ssitu/ComfyUI_fabric/issues/7)

Advice was to update comfyui, but that seems to make the node act like a vanilla sampler, where null conditioning and latents have no effect on the image generation.

**Comment by ssitu** [comment]
There have been a ton of updates to Comfy that I haven't had the chance to update this repo for. There's been pull requests made to remedy that, but looks like it caused the algorithm to stop working. If you are willing to use the older version of ComfyUI, you will need the commit of this repo before the pull requests, which is e5e8897539853a77d20e5a364010f3d73e5d6f6d. Also it looks like I neglected to update the readme about the comfyui commit, I believe it is this commit where it should be working: https://github.com/comfyanonymous/ComfyUI/commit/2ef459b1d4d627929c84d11e5e0cbe3ded9c9f48

**Comment by revolvedai** [comment]
Ah that explains so much! Very interested in these nodes and hope they eventually get updated to work with all the fun new stuff in ComfyUI

**Comment by ssitu** [comment]
This should be fixed now.

**Comment by motelaus** [comment]
> This should be fixed now.

can confirm it works again! Ty!
