### ISSUE TITLE
AttributeError: module 'comfy.samplers' has no attribute 'wrap_model'

### ISSUE THREAD

**Issue by chrisgoringe** [ssitu/ComfyUI_fabric#7]
```
File "...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_fabric\fabric\fabric.py", line 42, in fabric_sample        
    timesteps = get_timesteps(model, steps, sampler_name, scheduler, denoise)
  File "...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_fabric\fabric\unet.py", line 22, in get_timesteps
    model_wrap = comfy.samplers.wrap_model(real_model)
AttributeError: module 'comfy.samplers' has no attribute 'wrap_model'
```

unet.py line 22 reads `    model_wrap = comfy.samplers.wrap_model(real_model)`

should it be `    model_wrap = sampler.model_wrap`  ?

**Comment by ssitu** [comment]
Is your ComfyUI up to date?

**Comment by chrisgoringe** [comment]
It is now :)

**Comment by poisenbery** [comment]
> Is your ComfyUI up to date?

The front page of the repo says that this was tested on https://github.com/comfyanonymous/ComfyUI/commit/07691e80c3bf9be16c629169e259105ca5327bf0 commit.

The "Up to Date" version of ComfyUI does not seem to actually use the latents or null conditioning.

When I made a separate install for ComfyUI using the commit that this was said to work on, I get the error message.


Which version does this actually work on??? When we use the one specified, there is error, but your advice is to "Update ComfyUI"

**Comment by chrisgoringe** [comment]
See https://github.com/ssitu/ComfyUI_fabric/issues/19

Looks like the fabric nodes aren't working any more.
